# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # provide the code to aws
  Build-deploy:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: create credentials
         run: |
           pwd
           cd ~
           mkdir .aws
           cd .aws
           echo "${{secrets.YMIR}}" > credentials
           aws s3 ls
       - name: deploy
         run: |
          aws s3 cp dynamo/ s3://bigdata-ducuara/parcial3/dynamo --recursive
          aws s3 cp scraping/ s3://bigdata-ducuara/parcial3/scraping --recursive
